# Generated by Django 2.2.3 on 2024-05-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debugtalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='# write you code', verbose_name='python代码')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_runner.Project')),
            ],
            options={
                'verbose_name': '驱动文件表',
                'verbose_name_plural': '驱动文件表',
                'db_table': 'debugtalk',
            },
        ),
    ]
