# Generated by Django 2.2.3 on 2024-05-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0004_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='HOST配置名称')),
                ('value', models.TextField(verbose_name='配置值')),
                ('create_user', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_runner.Project')),
            ],
            options={
                'verbose_name': '环境配置表',
                'verbose_name_plural': '环境配置表',
                'db_table': 'hostip',
            },
        ),
    ]
