# Generated by Django 5.0.6 on 2024-05-31 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0006_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pycode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.TextField(default='# _*_ coding:utf-8 _*_', verbose_name='python代码')),
                ('name', models.CharField(max_length=30, verbose_name='驱动文件名')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='简要介绍')),
                ('create_user', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_runner.project')),
            ],
            options={
                'verbose_name': '驱动文件库',
                'verbose_name_plural': '驱动文件库',
                'db_table': 'pycode',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
