# Generated by Django 5.0.6 on 2024-05-31 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0007_pycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=500, verbose_name='接口名称')),
                ('body', models.TextField(verbose_name='主体信息')),
                ('url', models.CharField(max_length=500, verbose_name='请求地址')),
                ('method', models.CharField(max_length=10, verbose_name='请求方式')),
                ('create_user', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('relation', models.CharField(max_length=50, verbose_name='节点id')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_runner.project')),
            ],
            options={
                'verbose_name': 'API信息表',
                'verbose_name_plural': 'API信息表',
                'db_table': 'api',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('apicaseid', models.CharField(max_length=50, null=True, verbose_name='api用例id')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('relation', models.CharField(max_length=50, verbose_name='节点id')),
                ('length', models.IntegerField(verbose_name='API个数')),
                ('tag', models.IntegerField(choices=[(1, '冒烟用例'), (2, '集成用例'), (3, '监控脚本'), (4, '回归用例'), (5, '系统用例'), (6, '空库用例')], default=2, verbose_name='用例标签')),
                ('create_user', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_runner.project')),
            ],
            options={
                'verbose_name': '用例信息表',
                'verbose_name_plural': '用例信息表',
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', models.TextField(default=[], verbose_name='结构主题')),
                ('type', models.IntegerField(default=1, verbose_name='树类型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_runner.project')),
            ],
            options={
                'verbose_name': '树形结构关系',
                'verbose_name_plural': '树形结构关系',
                'db_table': 'relation',
            },
        ),
    ]
