# Generated by Django 5.0.6 on 2024-06-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0008_api_case_relation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStep",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="用例名称")),
                ("body", models.TextField(verbose_name="主体信息")),
                ("url", models.CharField(max_length=500, verbose_name="请求地址")),
                ("method", models.CharField(max_length=10, verbose_name="请求方式")),
                ("step", models.IntegerField(verbose_name="顺序")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_runner.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例执行步骤表",
                "verbose_name_plural": "用例执行步骤表",
                "db_table": "casestep",
            },
        ),
    ]
