# Generated by Django 2.2.3 on 2024-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0002_debugtalk'),
        ('test_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='belong_project',
            field=models.ManyToManyField(blank=True, help_text='所属项目', related_name='user_set', related_query_name='user', to='test_runner.Project'),
        ),
    ]
